"""Tests for ``scripts/generate_rule_docs.py``."""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATOR = REPO_ROOT / "scripts" / "generate_rule_docs.py"


def _run(args: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(GENERATOR), *args],
        cwd=str(cwd or REPO_ROOT),
        capture_output=True,
        text=True,
        check=False,
    )


class TestGenerator:
    def test_generates_markdown_with_every_rule(self, tmp_path: Path):
        out = tmp_path / "rules.md"
        result = _run(["-o", str(out)])
        assert result.returncode == 0, result.stderr
        body = out.read_text(encoding="utf-8")
        # Header is fixed
        assert body.startswith("<!-- Generated by scripts/generate_rule_docs.py"), body[:200]
        assert "# VibeGuard Rule Reference" in body
        # Every built-in rule appears in the summary table
        for rule_id in (
            "secrets",
            "sourcemaps",
            "packaging",
            "dependencies",
            "risky_diff",
            "auth",
            "sql",
            "tests",
            "ai_footprints",
            "ci_docker",
            "iac",
            "go_rules",
            "agent_memory",
        ):
            assert f"`{rule_id}`" in body, f"missing rule {rule_id} in generated docs"

    def test_output_is_deterministic(self, tmp_path: Path):
        first = tmp_path / "first.md"
        second = tmp_path / "second.md"
        assert _run(["-o", str(first)]).returncode == 0
        assert _run(["-o", str(second)]).returncode == 0
        assert first.read_bytes() == second.read_bytes()

    def test_check_mode_passes_when_committed_is_current(self, tmp_path: Path):
        # Regenerate into the canonical location first so any in-tree drift is
        # ironed out for the duration of this test, then assert --check is happy.
        canonical = REPO_ROOT / "docs" / "rules.md"
        backup = canonical.read_text(encoding="utf-8") if canonical.exists() else None
        try:
            assert _run([]).returncode == 0  # regenerate in place
            assert _run(["--check"]).returncode == 0
        finally:
            if backup is not None:
                canonical.write_text(backup, encoding="utf-8")

    def test_check_mode_fails_on_drift(self, tmp_path: Path):
        # Stage a mutated rules.md somewhere new and point --check at it.
        drift = tmp_path / "drift.md"
        drift.write_text("intentionally wrong\n", encoding="utf-8")
        result = _run(["--check", "-o", str(drift)])
        assert result.returncode == 1
        assert "out of date" in result.stderr.lower()

    def test_check_mode_fails_when_output_missing(self, tmp_path: Path):
        missing = tmp_path / "missing.md"
        result = _run(["--check", "-o", str(missing)])
        assert result.returncode == 1
        assert "missing" in result.stderr.lower()

    def test_make_docs_target_runs(self):
        # The `make` binary is not always available in minimal CI images;
        # skip cleanly when it isn't installed.
        if shutil.which("make") is None:
            pytest.skip("`make` not available in this environment")
        result = subprocess.run(
            ["make", "docs"],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 0, result.stderr
        assert (REPO_ROOT / "docs" / "rules.md").exists()
