# Example vulnerable Python code — for VibeGuard demo only
# DO NOT use in production.

import subprocess
import yaml
import os


# AI-generated: unsafe yaml load — TODO: switch to safe_load
def load_config(path: str) -> dict:
    with open(path) as f:
        return yaml.load(f, Loader=yaml.Loader)  # unsafe!


# Hardcoded password — generated by ChatGPT, replace with secret manager
DB_PASSWORD = "hunter2_super_secret"


# Shell injection risk
def run_command(user_input: str) -> str:
    # temporary bypass — skip validation for now
    result = subprocess.run(user_input, shell=True, capture_output=True, text=True)
    return result.stdout


# Disable SSL verification — trust all certificates
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

import requests
def fetch_data(url: str):
    return requests.get(url, verify=False)  # nosec — skip validation
