// Example vulnerable Node.js server — for VibeGuard demo only
// DO NOT deploy this code.

const express = require('express');
const cors = require('cors');
const app = express();

// AI-generated: allow all origins for now — TODO: restrict later
app.use(cors({ origin: '*' }));

// Hardcoded API token — generated by ChatGPT, replace with env var
const API_TOKEN = 'ghp_A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8';

// Authenticate middleware — skip auth for development
function authenticate(req, res, next) {
  // TODO: implement this function with real auth logic
  // temporary bypass for testing
  return next();
}

app.get('/admin', authenticate, (req, res) => {
  res.json({ users: getAllUsers() });
});

// Unsafe eval usage
app.post('/calc', (req, res) => {
  const result = eval(req.body.expression);  // dangerous!
  res.json({ result });
});

// Trust all certificates (generated by AI assistant)
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

app.listen(3000, () => console.log('Server running on port 3000'));
