#!/usr/bin/env python3
"""Generate ``docs/rules.md`` from the rule metadata registry.

The generator is the canonical writer for the rule reference page. CI runs
``python scripts/generate_rule_docs.py --check`` to fail the build when a
rule edit hasn't been mirrored into the committed docs — the same pattern
``ruff format --check`` uses.

Usage::

    python scripts/generate_rule_docs.py           # write docs/rules.md
    python scripts/generate_rule_docs.py --check   # exit 1 if drift detected
    python scripts/generate_rule_docs.py -o path/to/rules.md
"""

from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from vibeguard import __version__  # noqa: E402
from vibeguard.rules.registry import RULE_REGISTRY, RuleMetadata  # noqa: E402

DEFAULT_OUTPUT = REPO_ROOT / "docs" / "rules.md"


def _ensure_rules_loaded() -> None:
    """Import every built-in rule module so ``RULE_REGISTRY`` is populated."""
    from vibeguard.rules import load_all_builtin_rules

    load_all_builtin_rules()


def _slug(rule_id: str) -> str:
    """Return a stable anchor for a rule heading."""
    return rule_id.lower().replace("_", "-").replace(" ", "-")


def _md_escape(text: str) -> str:
    """Escape Markdown special characters in inline text.

    Only the pipe character is escaped — it is the only special character
    that breaks markdown table cell boundaries. Backticks are intentionally
    left alone because they render as inline code within cells (desired
    behaviour for rule descriptions that reference identifiers).
    """
    return text.replace("|", "\\|")


def _render_summary_row(meta: RuleMetadata) -> str:
    finding_count = len(meta.finding_ids)
    applies = ", ".join(meta.applies_to) if meta.applies_to else "*"
    tags = ", ".join(meta.tags) if meta.tags else "—"
    config_key = meta.config_key or meta.rule_id
    return (
        f"| [`{meta.rule_id}`](#{_slug(meta.rule_id)}) "
        f"| {_md_escape(meta.title)} "
        f"| `{config_key}` "
        f"| {meta.default_severity} "
        f"| {meta.confidence} "
        f"| {finding_count} "
        f"| {_md_escape(tags)} "
        f"| {_md_escape(applies)} |"
    )


def _render_rule_section(meta: RuleMetadata) -> str:
    out = io.StringIO()
    out.write(f'<a id="{_slug(meta.rule_id)}"></a>\n\n')
    out.write(f"### `{meta.rule_id}` — {meta.title}\n\n")
    out.write(meta.description.rstrip())
    out.write("\n\n")
    config_key = meta.config_key or meta.rule_id
    out.write(
        f"- **Default severity:** `{meta.default_severity}`\n"
        f"- **Confidence:** `{meta.confidence}`\n"
        f"- **Config section:** `{config_key}` (in `vibeguard.yaml`)\n"
        f"- **Tags:** {', '.join(f'`{t}`' for t in meta.tags) if meta.tags else '_none_'}\n"
        f"- **Applies to:** "
        f"{', '.join(f'`{p}`' for p in meta.applies_to) if meta.applies_to else '`*`'}\n"
    )
    if meta.docs_url:
        out.write(f"- **Docs:** <{meta.docs_url}>\n")
    out.write("\n**Finding IDs**\n\n")
    if meta.finding_ids:
        if meta.remediations:
            # Render finding IDs as a definition list of id → remediation so
            # the generated docs surface the same "how to fix" text the
            # ``vibeguard explain`` command renders.
            for fid in meta.finding_ids:
                remediation = meta.remediations.get(fid.upper())
                if remediation:
                    out.write(f"- `{fid}` — {_md_escape(remediation)}\n")
                else:
                    out.write(f"- `{fid}`\n")
        else:
            for fid in meta.finding_ids:
                out.write(f"- `{fid}`\n")
    else:
        out.write("_(none registered yet)_\n")
    if meta.examples:
        out.write("\n**Examples**\n\n")
        for example in meta.examples:
            label = example.get("label") or example.get("name") or "Example"
            code = example.get("code") or example.get("body") or ""
            lang = example.get("language") or example.get("lang") or ""
            out.write(f"_{_md_escape(label)}_\n\n")
            out.write(f"```{lang}\n{code.rstrip()}\n```\n\n")
    out.write("\n")
    return out.getvalue()


def render_rules_markdown() -> str:
    """Build the full ``docs/rules.md`` body as a string."""
    _ensure_rules_loaded()

    rule_ids = sorted(RULE_REGISTRY.keys())
    out = io.StringIO()
    out.write(f"<!-- Generated by scripts/generate_rule_docs.py from vibeguard {__version__}. -->\n")
    out.write("<!-- DO NOT EDIT BY HAND — run `make docs`. -->\n\n")
    out.write("# VibeGuard Rule Reference\n\n")
    out.write(
        "This page is generated from the rule metadata registry "
        "(`vibeguard/rules/registry.py`). Every rule documented below ships "
        "in the `vibeguard` package; third-party rules contributed via the "
        "[plugin API](plugin-api.md) appear at runtime in "
        "`vibeguard rules list`.\n\n"
    )
    out.write("## Summary\n\n")
    out.write(
        "| Rule | Title | Config section | Default severity | Confidence | Findings "
        "| Tags | Applies to |\n"
    )
    out.write(
        "|------|-------|----------------|------------------|------------|----------"
        "|------|------------|\n"
    )
    for rule_id in rule_ids:
        out.write(_render_summary_row(RULE_REGISTRY[rule_id]) + "\n")
    out.write("\n## Rules\n\n")
    for rule_id in rule_ids:
        out.write(_render_rule_section(RULE_REGISTRY[rule_id]))
    text = out.getvalue()
    # Collapse any accidental triple-blank-line runs introduced by section
    # joining so the output is byte-stable across regenerations.
    while "\n\n\n\n" in text:
        text = text.replace("\n\n\n\n", "\n\n\n")
    if not text.endswith("\n"):
        text += "\n"
    return text


def _normalize(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output path (default: {DEFAULT_OUTPUT.relative_to(REPO_ROOT)})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 if the generated content differs from --output",
    )
    args = parser.parse_args(argv)

    body = render_rules_markdown()

    if args.check:
        try:
            committed = _normalize(args.output.read_text(encoding="utf-8"))
        except FileNotFoundError:
            print(
                f"[generate_rule_docs] {args.output} is missing. "
                f"Run `make docs` to generate it.",
                file=sys.stderr,
            )
            return 1
        generated = _normalize(body)
        if committed != generated:
            print(
                f"[generate_rule_docs] {args.output} is out of date. "
                f"Run `make docs` to regenerate.",
                file=sys.stderr,
            )
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(body, encoding="utf-8")
    try:
        # Only display the relative path when the output actually lives
        # inside the repo; otherwise (CI tmp dirs, ad-hoc paths) show the
        # full path so the user knows where the file landed.
        display = str(args.output.relative_to(REPO_ROOT))
    except ValueError:
        display = str(args.output)
    print(f"[generate_rule_docs] wrote {display}")
    return 0


if __name__ == "__main__":  # pragma: no cover — CLI entry point
    sys.exit(main())
